name: CI

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'etc/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        emacs_version: ['release-snapshot']
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Check emacs version
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - name: Run tests
      run: make test
